### ISSUE TITLE
Interface conversion problem

### ISSUE THREAD

**Issue by jpaulm** [jpaulm/gofbp#9]
No compile error - run time problem

I think my `list` contains `*Process` elements, but somehow they are being treated as `Process` elements...!

```
panic: interface conversion: interface {} is core.Process, not *core.Process

goroutine 1 [running]:
github.com/jpaulm/gofbp/core.(*Network).Run(0xc0000c2450)
        C:/Users/Paul/Documents/GitHub/gofbp/core/network.go:55 +0x1ed
main.main()
        C:/Users/Paul/Documents/GitHub/gofbp/main.go:18 +0x18f
```

**Comment by jpaulm** [comment]
I have followed someone's advice, and switched to using a slice instead of a List.  Axccordingly I am closing this, as I don't have time to work on it!

**Comment by jpaulm** [comment]
Just to say I raised this again as #11 - I will investigate further if I have time!
